### ISSUE TITLE
Version posted to grammars-v4/rexx is unlicensed

### ISSUE THREAD

**Issue by RossPatterson** [candiduslynx/antlr4-rexx#2]
Thanks for creating this!  I see you committed a copy to https://github.com/antlr/grammars-v4/tree/master/rexx back in 2017.  As the original author, would you mind also pushing the LICENSE file?  Right now, the license at grammars-v4 isn't clear, because the repo explicitly doesn't have a default license.

Thanks,
Ross
Former SHARE VM-er and occasional drinking buddy of Mike Cowlishaw.]

**Comment by candiduslynx** [comment]
Hello!
Do you need me to push the license file here or explicitly to https://github.com/antlr/grammars-v4/tree/master/rexx?

**Comment by RossPatterson** [comment]
I'd appreciate it if you would push it to
https://github.com/antlr/grammars-v4/tree/master/rexx.

Thanks!

Ross

**Comment by candiduslynx** [comment]
https://github.com/antlr/grammars-v4/pull/2529

**Comment by RossPatterson** [comment]
Thanks!
