### ISSUE TITLE
Are you interested in updates?

### ISSUE THREAD

**Issue by RossPatterson** [candiduslynx/antlr4-rexx#3]
I have an update that makes it possible to generate a Python parser from this grammar , without removing the default ability to generate a Java parser.  I also have an update that breaks apart the two different kinds of concatenation - abuttal (_i.e._, the || operator, and abuttal of values) and joining-with-one-blank (_i.e._, concatenation by intervening whitespace).  If you're interested in them, I'll package up a PR for you to review and merge.  If not, that's fine.  Either way, I intend to send them to the antlr/grammars-v4 repository.

**Comment by candiduslynx** [comment]
Hi!
Thanks for the proposal!
I think it's better to do the update to the `antlr/grammars-v4` repo, as it has a [copy](https://github.com/antlr/grammars-v4/tree/master/rexx) of this repo already.

I'll archive this repository, so that everyone knows that it's no longer actively maintained.
